#ifndef __glCmdAndStructPrint2_h__2013_10_28__
#define __glCmdAndStructPrint2_h__2013_10_28__

//集中管理模式，共享打印机信息，操作类型
enum REQ_PRINTSHAREPRINTERINFO_TYPE
{
	REQ_SHARE_FROM_DB = 0,		//从数据库中请求
	REQ_SHARE_ADD_BY_PRT = 1,//打印站点自动添加
	REQ_SHARE_ADD_BY_TOOL = 2,	//通过工具自动添加
	REQ_SHARE_CHECK_PRT_INFO = 3,	//检测打印站点配置信息
	REQ_SHARE_DEL_BY_PRT = 4,	//删除打印站点配置信息
	REQ_SHARE_DEL_BY_TOOL = 5	//删除打印站点配置信息
};

#define  IST_BASE_6000	6000
#define  WM_IST_PRINT2		WM_USER + IST_BASE_6000


enum ISEC_PORT
{
	ISEC_PORT_WEB_CTRL = 5030,
	ISEC_PORT_WEB_KEMEIPRINT = 50111
};

enum EXE_TYPE
{
	ISECASVCHOST = 1,	//中心服务器
	ISECTIMERTOOL,		//定时工具
	ISECCLOUDDOCHELPER	//云转换工具
};

#define	VERSION_CODE_5602 TEXT("5.6.0.2")
#define	VERSION_CODE_5603 TEXT("5.6.0.3")

//打印日志-成绩打印
#define WM_REQ_PRINT_LOG_TRANSCRIPT				WM_IST_PRINT2 + 60
#define WM_REQ_PRINT_LOG_FILE_TRANSCRIPT		WM_IST_PRINT2 + 61
#define WM_REQ_PRINT_LOG_FILE_END_TRANSCRIPT	WM_IST_PRINT2 + 62
#define WM_PUSH_PRINT_LOG_FILE_TRANSCRIPT		WM_IST_PRINT2 + 63
#define WM_ALL_PRINT_LOG_END_TRANSCRIPT			WM_IST_PRINT2 + 64
#define WM_PRINT_FLAG_TRANSCRIPT				WM_IST_PRINT2 + 65
#define WM_REQ_PRINT_LOG_TRANSCRIPT_ENTRUST		WM_IST_PRINT2 + 66
#define WM_CHECK_TIMER_TOOL						WM_IST_PRINT2 + 67
#define WM_CHECK_PRT_STATION_STATE				WM_IST_PRINT2 + 68

//打印日志-准考证打印
#define WM_REQ_PRINT_LOG_ADMISSION				WM_IST_PRINT2 + 70
#define WM_REQ_PRINT_LOG_FILE_ADMISSION			WM_IST_PRINT2 + 71
#define WM_REQ_PRINT_LOG_FILE_END_ADMISSION		WM_IST_PRINT2 + 72
#define WM_PUSH_PRINT_LOG_FILE_ADMISSION		WM_IST_PRINT2 + 73
#define WM_ALL_PRINT_LOG_END_ADMISSION			WM_IST_PRINT2 + 74
#define WM_PRINT_FLAG_ADMISSION					WM_IST_PRINT2 + 75

#define WM_PRINT_STATION_CHARGE_ON_PRINT_TRANSCRIPT		WM_IST_PRINT2 + 81 //打印站点成绩打印预计扣费
#define WM_PRINT_STATION_CHARGE_ON_PRINT_ADMISSION		WM_IST_PRINT2 + 82 //打印站点准考证打印预计扣费
#define WM_PRINT_STATION_CHARGE_ON_PRINT_USBPRINT		WM_IST_PRINT2 + 83 //打印站点usb打印预计扣费
#define WM_PRINT_STATION_CHARGE_ON_PRINT_LEAVESCHOOL	WM_IST_PRINT2 + 84 //打印站点离校单打印预计扣费
#define WM_PRINT_STATION_CHARGE_ON_PRINT_CLOUD			WM_IST_PRINT2 + 85 //打印站点云打印计费
#define WM_PRINT_STATION_CHARGE_ON_PRINT_NOTICE			WM_IST_PRINT2 + 86 //打印站点公告打印计费

//打印日志-USB打印
#define WM_REQ_PRINT_LOG_USBPRINT				WM_IST_PRINT2 + 90
#define WM_REQ_PRINT_LOG_FILE_USBPRINT			WM_IST_PRINT2 + 91
#define WM_REQ_PRINT_LOG_FILE_END_USBPRINT		WM_IST_PRINT2 + 92
#define WM_PUSH_PRINT_LOG_FILE_USBPRINT			WM_IST_PRINT2 + 93
#define WM_ALL_PRINT_LOG_END_USBPRINT			WM_IST_PRINT2 + 94
#define WM_PRINT_FLAG_USBPRINT					WM_IST_PRINT2 + 95

//成绩单导入工具
#define WM_PRINT_TRANSCRIPT_DB_INFO				WM_IST_PRINT2 + 100 //数据库配置信息
#define WM_PRINT_TRANSCRIPT_TOOL_LOGON			WM_IST_PRINT2 + 101 //管理员登录

//打印日志-离校单打印
#define WM_REQ_PRINT_LOG_LEAVESCHOOL				WM_IST_PRINT2 + 110
#define WM_REQ_PRINT_LOG_FILE_LEAVESCHOOL			WM_IST_PRINT2 + 111
#define WM_REQ_PRINT_LOG_FILE_END_LEAVESCHOOL		WM_IST_PRINT2 + 112
#define WM_PUSH_PRINT_LOG_FILE_LEAVESCHOOL			WM_IST_PRINT2 + 113
#define WM_ALL_PRINT_LOG_END_LEAVESCHOOL			WM_IST_PRINT2 + 114
#define WM_PRINT_FLAG_LEAVESCHOOL					WM_IST_PRINT2 + 115
#define WM_REQ_PRINT_LOG_LEAVESCHOOL_ENTRUST		WM_IST_PRINT2 + 116

//打印日志-云打印
#define WM_REQ_PRINT_LOG_CLOUD						WM_IST_PRINT2 + 120	//请求打印任务
#define WM_REQ_PRINT_LOG_FILE_CLOUD					WM_IST_PRINT2 + 121	//请求打印文件
#define WM_REQ_PRINT_LOG_FILE_END_CLOUD				WM_IST_PRINT2 + 122	//请求打印文件结束
#define WM_PUSH_PRINT_LOG_FILE_CLOUD				WM_IST_PRINT2 + 123	//推送云打印
#define WM_ALL_PRINT_LOG_END_CLOUD					WM_IST_PRINT2 + 124	//所有云打印完成
#define WM_PRINT_FLAG_CLOUD							WM_IST_PRINT2 + 125	//云打印标记
#define WM_PRINT_STATION_DEL_JOB_CLOUD				WM_IST_PRINT2 + 126	//打印站点删除云打印作业

//打印日志-公告打印
#define WM_REQ_PRINT_LOG_NOTICE					    WM_IST_PRINT2 + 130
#define WM_REQ_PRINT_LOG_FILE_NOTICE			    WM_IST_PRINT2 + 131
#define WM_REQ_PRINT_LOG_FILE_END_NOTICE		    WM_IST_PRINT2 + 132
#define WM_PUSH_PRINT_LOG_FILE_NOTICE			    WM_IST_PRINT2 + 133
#define WM_ALL_PRINT_LOG_END_NOTICE				    WM_IST_PRINT2 + 134
#define WM_PRINT_FLAG_NOTICE					    WM_IST_PRINT2 + 135

//成绩、证件、公告打印快照
#define WM_PRINT_SNAPSHOOT_LOG					    WM_IST_PRINT2 + 140
#define WM_PRINT_SNAPSHOOT_FILE_BEGIN			    WM_IST_PRINT2 + 141
#define WM_PRINT_SNAPSHOOT_FILE_DATA			    WM_IST_PRINT2 + 142
#define WM_PRINT_SNAPSHOOT_FILE_END					WM_IST_PRINT2 + 143
#define WM_ALL_PRINT_SNAPSHOO_END				    WM_IST_PRINT2 + 144
#define WM_PRINT_FLAG_SNAPSHOOT						WM_IST_PRINT2 + 145


//打印小票
#define WM_TICKET_REQ_PURCHASE_LOG				    WM_IST_PRINT2 + 150
#define WM_TICKET_UPLOAD_PURCHASE_LOG			    WM_IST_PRINT2 + 151
#define WM_TICKET_UPDATE_PURCHASE_LOG			    WM_IST_PRINT2 + 152


#define WM_PRINT_PHONE_CHARGE					    WM_IST_PRINT2 + 200	//移动支付
#define WM_PRINT_PHONE_LOGIN						WM_IST_PRINT2 + 201	//移动登录

//成绩、证件、公告打印人拍照
#define WM_PRINT_CAMERA_LOG						    WM_IST_PRINT2 + 202
#define WM_PRINT_CAMERA_FILE_BEGIN					WM_IST_PRINT2 + 203
#define WM_PRINT_CAMERA_FILE_DATA					WM_IST_PRINT2 + 204
#define WM_PRINT_CAMERA_FILE_END					WM_IST_PRINT2 + 205
#define WM_ALL_PRINT_CAMERA_END						WM_IST_PRINT2 + 206
#define WM_PRINT_FLAG_CAMERA						WM_IST_PRINT2 + 207


//webinf通知服务器
#define WM_WEB_NOTIFY_SERVER_REQ					WM_IST_PRINT2 + 300	//web请求服务器
#define WM_WEB_NOTIFY_SERVER_ACK					WM_IST_PRINT2 + 301 //web请求服务器之后服务器的回应

#define WM_PRINT_STATTON_REQ_ORDER					WM_IST_PRINT2 + 400	//(7424)请求定单信息
#define	WM_UPDATE_PRINT_STATTON_ALERT_STATUS		WM_IST_PRINT2 + 401	//(7425)更新打印站点预警状态
#define WM_UPDATE_PRINT_STATION						WM_IST_PRINT2 + 402	//(7426)更新打印站点
#define WM_PRINT_THIRDPAY_LOGIN_INFO					WM_IST_PRINT2 + 403	//(7427)第三方登录信息,保留
#define WM_PRINT_USER_LOGOFF						WM_IST_PRINT2 + 404	//(7428)打印站点用户注销
#define WM_ROUTER_PRINTER_ADD						WM_IST_PRINT2 + 405	//(7429)打印网关添加打印机
#define WM_ROUTER_PRINTER_DELETE					WM_IST_PRINT2 + 406	//(7430)打印网关删除打印机
#define WM_ROUTER_PRINTER_UPDATE					WM_IST_PRINT2 + 407	//(7431)打印网关更新打印机
#define WM_PRINT_STATTON_INFO_LIST					WM_IST_PRINT2 + 408	//(7432)打印网关请求打印机列表信息
#define WM_ROUTER_EQUIP_INFO						WM_IST_PRINT2 + 409	//(7433)打印网关设备信息
#define WM_PRINT_STATTON_RUN_STATE					WM_IST_PRINT2 + 410	//(7434)打印站点运行状态
#define WM_NOTIFY_UPDATE_PRTLIST					WM_IST_PRINT2 + 411	//(7435)通知更新站点列表
#define WM_USER_PROJECT_INFO_LIST					WM_IST_PRINT2 + 412	//(7436)用户项目信息列表
#define WM_EMBED_REQ_PRINT_STATION					WM_IST_PRINT2 + 413	//(7437)内嵌向中心服务器请求站点信息，目前是连接信息 ip和端口号
#define WM_WEB_NOTIFY_METER_OID_CHANGED				WM_IST_PRINT2 + 414	//(7438)
#define WM_NOTIFY_DIRECT_PRINT						WM_IST_PRINT2 + 415	//(7439)通知直打作业
#define WM_WEB_NOTIFY_UPDATEACCOUNTQUOTA				WM_IST_PRINT2 + 416	//(7440)通知更新配额
#define WM_WEB_NOTIFY_LOGIN_PRT						WM_IST_PRINT2 + 417	//(7441)通知站点登录
#define WM_WEB_NOTIFY_OCR							WM_IST_PRINT2 + 418	//(7442)OCR检索相关
#define WM_WEB_NOTIFY_OCR_RESULT					WM_IST_PRINT2 + 419	//(7443)通知ocr结果
#define WM_WEB_NOTIFY_SEARCH_OCR					WM_IST_PRINT2 + 420	//(7444)通知检索OCR
#define WM_WEB_NOTIFY_GET_OCRTEXT					WM_IST_PRINT2 + 421	//(7445)请求OCR结果内容
#define WM_WEB_NOTIFY_CHANGE_KEYWORD					WM_IST_PRINT2 + 422	//(7446)添加或删除关键字
#define WM_DEL_JOB_OCRTEXT							WM_IST_PRINT2 + 423	//(7447)删除OCR内容
#define WM_Web_AddOrUpdateArm						WM_IST_PRINT2 + 424	//(7448)添加或更新arm信息
#define WM_AddOrUpdateArmPrtAck						WM_IST_PRINT2 + 425	//(7449)添加或更新arm信息 站点回复
#define WM_Web_DownloadArmLog						WM_IST_PRINT2 + 426	//(7450)下载arm日志
#define WM_Update_ArmOnLineState					WM_IST_PRINT2 + 427	//(7451)arm在线状态
#define WM_Arm_UploadLogRes							WM_IST_PRINT2 + 428	//(7452)arm日志上传状态
#define WM_Arm_CheckUpdateReq						WM_IST_PRINT2 + 429	//(7453)arm检查升级
#define WM_Arm_CheckUpdateAck						WM_IST_PRINT2 + 430	//(7453)arm检查升级结果
#define WM_ARM_UpgradeSucNotify						WM_IST_PRINT2 + 431	//(7454)arm升级成功通知

#define WM_PRINT_PRINTER_METER_INFO					WM_IST_PRINT2 + 501 //(7525)打印机抄表信息
#define WM_PRINT_SHARE_PRINTER_INFO					WM_IST_PRINT2 + 502	//(7526)共享打印机信息
#define WM_PRINT_BAK_INFO							WM_IST_PRINT2 + 503	//(7527)打印留底信息



#define WM_REQ_PRINT_DOCUMENT						WM_IST_PRINT2 + 520 //(7544)
#define WM_REQ_CONVERT_DOCUMENT						WM_IST_PRINT2 + 521 //(7545)

#define WM_ADD_FILE_STORAGE_INFO					WM_IST_PRINT2 + 530	//(7554)添加文件存储信息
#define WM_UPDATE_FILE_STORAGE_INFO					WM_IST_PRINT2 + 531	//(7555)更新文件存储信息
#define WM_REQ_UNPARSEED_SPL_JOB					WM_IST_PRINT2 + 532	//(7556)获取未转换的spl作业
#define WM_UPDATE_SPL_JOB							WM_IST_PRINT2 + 533	//(7557)更新spl作业信息
#define WM_GET_OUT_DATE_JOB							WM_IST_PRINT2 + 534	//(7558)获取过期作业信息
#define WM_UPDATE_OUT_DATE_JOB						WM_IST_PRINT2 + 535	//(7559)更新过期作业信息

#endif
